# SPDX-License-Identifier: Apache-2.0.
# Copyright (C) 2026-present indtp project and contributors.

# Project package info section.
[package]
name        = "indtp"
version     = "0.1.0"
description = "Inertial Navigation Data Transfer Protocol (INDTP)"
authors     = ["Alexander <alkuzindev@gmail.com>"]
repository  = "https://github.com/alkuzin/indtp"
license     = "Apache-2.0"
edition     = "2024"

# Project dependencies section.
[dependencies]
# Zerocopy makes zero-cost memory manipulation effortless.
zerocopy = { version = "0.8", features = ["derive"] }

# Project features section.
[features]
# Features that used by default.
default = []
