# SPDX-License-Identifier: Apache-2.0.
# Copyright (C) 2026-present indtp project and contributors.

# Project package info section.
[package]
name        = "indtp"
version     = "0.6.0"
description = "Inertial Navigation Data Transfer Protocol (INDTP)"
authors     = ["Alexander <alkuzindev@gmail.com>"]
repository  = "https://github.com/alkuzin/indtp"
license     = "Apache-2.0"
edition     = "2024"

# Project features section.
[features]
# Features that used by default.
default = ["sw_impl", "std_payloads"]
# Feature to enable software-based calculation for
# integrity checks & cryptography.
sw_impl = ["sw_integrity", "sw_crypto"]
# Feature to enable software-based calculation for integrity checks.
sw_integrity = ["dep:crc"]
# Feature to enable software-based calculation for cryptography.
sw_crypto = ["dep:hmac", "dep:cmac", "dep:sha2", "dep:aes", "dep:ctr"]
# Feature that enables standard payloads.
std_payloads = []

# Project dependencies section.
[dependencies]
# Zerocopy makes zero-cost memory manipulation effortless.
zerocopy = { version = "0.8", features = ["derive"] }
# Generate types for C-style flags with ergonomic APIs.
bitflags = "2.11.0"
# Rust implementation of CRC.
crc = { version = "3.4.0", optional = true }
# Generic implementation of Hash-based Message Authentication Code (HMAC).
hmac = { version = "0.12.1", optional = true }
# Generic implementation of Cipher-based Message Authentication Code (CMAC).
cmac = { version = "0.7.2", optional = true }
# An implementation of the SHA-2 cryptographic hash algorithms.
sha2 = { version = "0.10.9", optional = true, default-features = false }
# Implementation of the Advanced Encryption Standard (AES, a.k.a. Rijndael).
aes = { version = "0.8.4", optional = true, default-features = false }
# Generic implementations of CTR mode for block ciphers.
ctr = { version = "0.9.2", optional = true, default-features = false }

# Section of project dependencies that are used for
# compiling tests, examples, and benchmarks.
[dev-dependencies]
indtp = { path = ".", features = ["sw_impl"] }
